[project]
name = "TextEvolve"
version = "0.1.0"
description = ""
authors = ["Nick Ryan <nickcdryan@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai>=1.72.0",
    "sift-stack-py>=0.5.0",
]
